# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jep 'n Jabber
email: alice.e.simons@gmail.com
description: "Jep 'n Jabber is Burke's premier podcast on LIFE!"
subtitle: "Everything is game."
lang: en-us
author: Alice Simons
copyright: "CC-BY 4.0"
baseurl: "/jepnjabber" # the subpath of your site, e.g. /blog
url: "https://rachelzhang31.github.io" # the base hostname & protocol for your site
twitter_username: INSERTTWITTERUSER
github_username:  rachelzhang31

permalink: /:year/:title.html

#Timezone
timezone: United States/New York

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

theme: jekyll-theme-minimal
